#!/usr/bin/env python3
"""Publication figures for nmi_draft_v2. All data from existing result sets.

fig1_benchmark.png   — benchmark schematic (rounds, CAD chain, capital, pricing)
fig2_leaderboard.png — 39-system main ranking (dot chart, category colored)
fig3_failures.png    — three failures: domain collapse / weight mechanisms / memorization
fig4_substrates.png  — dose-response / JitRL slope / V2-vs-frontier distributions
fig6_judges.png      — judge-judge agreement + family-bias gaps
(fig5 = formal_model.png, generated by formal_model_sim.py)
"""
import json
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / 'paper' / 'figures'
FIG.mkdir(exist_ok=True)

# colorblind-safe, low-saturation palette
C_BLUE, C_ORANGE, C_GREEN, C_RED, C_PURPLE, C_GRAY = \
    '#4878a8', '#d98f4a', '#6a9f58', '#c05a5a', '#8a7ab5', '#9aa0a6'
plt.rcParams.update({
    'font.size': 9, 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.grid': True, 'grid.alpha': 0.25, 'grid.linestyle': '--', 'grid.linewidth': 0.5,
    'figure.dpi': 200,
})


def save(fig, name):
    fig.savefig(FIG / name, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print('saved', name)


# ═══════════════ Fig 1: benchmark schematic ═══════════════
def fig1():
    fig, ax = plt.subplots(figsize=(10.5, 4.4))
    ax.axis('off'); ax.set_xlim(0, 100); ax.set_ylim(-2, 46)

    def box(x, y, w, h, text, fc, ec, fs=8.5, bold=False):
        from matplotlib.patches import FancyBboxPatch
        ax.add_patch(FancyBboxPatch((x, y), w, h, fc=fc, ec=ec, lw=1.2,
                                    boxstyle='round,pad=0.4', mutation_aspect=0.5))
        ax.text(x + w / 2, y + h / 2, text, ha='center', va='center', fontsize=fs,
                fontweight='bold' if bold else 'normal', color='#222')

    def arrow(x1, y1, x2, y2, style='-', color='#555', lw=1.3):
        ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle='-|>', color=color, lw=lw, linestyle=style))

    # five-round strip
    rounds = [('R1 scratch\n(new product)', '#eef4fb'), ('R2 adapt\n(bigger product)', '#eef4fb'),
              ('R3 add bay', '#eef4fb'), ('R4 add module\n(combine all)', '#eef4fb'),
              ('R5 shrink\n(keep functions)', '#eef4fb')]
    x = 3
    for i, (t, fc) in enumerate(rounds):
        box(x, 33, 16, 9, t, fc, C_BLUE)
        if i < 4:
            arrow(x + 16.5, 37.5, x + 19.5, 37.5)
        x += 20
    ax.text(2, 43.2, 'five-round cumulative demands', fontsize=9, color='#555', style='italic')

    # generation + CAD chain
    box(8, 20, 20, 8, 'LLM design\n(workstation-csg JSON)', '#fdf6ee', C_ORANGE)
    arrow(18, 32.8, 18, 28.4)
    box(36, 20, 26, 8, 'build123d B-rep execution\nbuild → STEP → re-import', '#f2f7ef', C_GREEN)
    arrow(28.4, 24, 35.6, 24)
    box(68, 20, 26, 8, 'exact geometry metrics\noverlap · envelope', '#f2f7ef', C_GREEN)
    arrow(62.4, 24, 67.6, 24)
    ax.text(81, 15.2, 'invalid → ¥0', fontsize=8, color=C_RED, ha='center')

    # judge + sale
    box(36, 4, 22, 8, 'user-simulation judges\n(3-vendor median)', '#f6f1fa', C_PURPLE)
    arrow(66, 19.6, 58, 12.4)
    box(64, 4, 30, 8, 'sale: rating ≥ 5\n¥100 × speed(<10 s: 1.5× …)', '#eef4fb', C_BLUE)
    arrow(58.4, 8, 63.6, 8)

    # capital loop
    box(3, 4, 26, 8, 'capital registry\nexecuted design → STEP asset', '#fdf6ee', C_ORANGE)
    arrow(16, 12.4, 16, 19.6)          # registry feeds next design
    ax.annotate('', xy=(29, 3.2), xytext=(79, 2.2),                 # sale→registry return path
                arrowprops=dict(arrowstyle='-|>', color=C_ORANGE, lw=1.5,
                                connectionstyle='arc3,rad=0.12'))
    ax.text(97, 43.2, 'validated designs become free, faster capital for later rounds',
            fontsize=8.5, color=C_ORANGE, ha='right', style='italic')
    save(fig, 'fig1_benchmark.png')


# ═══════════════ Fig 2: leaderboard dot chart ═══════════════
def fig2():
    rows = [  # (name, profit, category)
        ('FluxEidosV2 system (3-judge)', 532, 'sys'), ('mimo-v2.6-flash (3-judge)', 433, 'com'),
        ('mimo-v2.6-pro (3-judge)', 418, 'com'), ('FluxEidosV1.5 weights', 390, 'own'),
        ('FluxEidosV1.0 + JitRL mature', 390, 'sys'), ('FluxEidosV1.0 (3-judge)', 387, 'own'),
        ('glm-5.3 (3-judge)', 380, 'com'), ('mimo-pro / flash (1-judge)', 377, 'com'),
        ('FluxEidosV1.0 (1-judge)', 372, 'own'), ('glm-5.3 (1-judge)', 338, 'com'),
        ('FluxEidosV1.5a JitRL accum.', 345, 'sys'), ('FluxEidosV1.1', 330, 'own'),
        ('glm-5.3-flash (3-judge)', 311, 'com'), ('V0.5 SFT only', 260, 'own'),
        ('V1.2 (over-trained)', 255, 'own'), ('V1.0-D distill (rejected)', 216, 'own'),
        ('qwen3.5-27B zero-shot', 213, 'zs'), ('V1.0-RSI weights (rejected)', 210, 'own'),
        ('gemma-4-12B zero-shot', 200, 'zs'), ('JitRL control (no memory)', 195, 'sys'),
        ('qwen3.8-27B UD-IQ3 zero-shot', 190, 'zs'), ('deepseek-flash V4.1', 174, 'com'),
    ]
    colors = {'sys': C_PURPLE, 'own': C_BLUE, 'com': C_ORANGE, 'zs': C_GRAY}
    labels = {'sys': 'our system entries', 'own': 'our weights', 'com': 'commercial API', 'zs': 'zero-shot open'}
    fig, ax = plt.subplots(figsize=(7.6, 7.2))
    names = [r[0] for r in rows][::-1]
    vals = [r[1] for r in rows][::-1]
    cats = [r[2] for r in rows][::-1]
    y = np.arange(len(rows))
    ax.hlines(y, 0, vals, color=[colors[c] for c in cats], lw=1.6, alpha=0.55)
    ax.scatter(vals, y, s=42, c=[colors[c] for c in cats], zorder=3)
    ax.set_yticks(y); ax.set_yticklabels(names, fontsize=8)
    for yi, v in zip(y, vals):
        ax.text(v + 6, yi, f'¥{v}', va='center', fontsize=7.5, color='#333')
    ax.axvline(433, color=C_ORANGE, lw=1, ls=':', alpha=0.8)
    ax.text(436, len(rows) - 0.5, 'frontier\n¥433', fontsize=7.5, color=C_ORANGE, va='top')
    ax.set_xlabel('profit per 5-round session (¥)')
    ax.set_xlim(0, 600)
    ax.grid(axis='y', visible=False)
    handles = [plt.Line2D([], [], marker='o', ls='', color=colors[k], label=labels[k])
               for k in ('sys', 'own', 'com', 'zs')]
    ax.legend(handles=handles, frameon=False, fontsize=8, loc='lower right')
    ax.set_title('39-system ranking (14 zero-shot systems at ¥0 not shown)', fontsize=9, loc='left')
    save(fig, 'fig2_leaderboard.png')


# ═══════════════ Fig 3: three failures ═══════════════
def fig3():
    fig, axes = plt.subplots(1, 3, figsize=(12.5, 3.6))
    # (a) domain collapse
    ax = axes[0]
    doms = ['workstation\n(in-domain)', 'fixture', 'layout']
    arms = {'mimo-v2.6-flash': ([433, 124, 138], C_ORANGE),
            'FluxEidosV1.5': ([390, 0, 60], C_BLUE),
            'FluxEidosV2': ([532, 0, 264], C_PURPLE)}
    w, x = 0.26, np.arange(3)
    for i, (k, (v, c)) in enumerate(arms.items()):
        b = ax.bar(x + (i - 1) * w, v, w * 0.92, color=c, label=k)
        for xi, vi in zip(x + (i - 1) * w, v):
            if vi:
                ax.text(xi, vi + 8, f'{int(100*vi/v[0])}%', ha='center', fontsize=7, color='#444')
    ax.set_xticks(x); ax.set_xticklabels(doms, fontsize=8)
    ax.set_ylabel('profit (¥)')
    ax.set_title('(a) domain shift degrades everyone', fontsize=9)
    ax.legend(frameon=False, fontsize=7.5)
    # (b) weight mechanisms vs noise floor
    ax = axes[1]
    mechs = ['V1.0\nbaseline', 'weight\nRSI', 'GAR-RL', 'TTRL', 'self-SFT\n(V0.2)']
    vals = [387, 210, 270, 270, 0]
    ax.bar(range(5), vals, 0.6, color=[C_BLUE] + [C_RED] * 4)
    ax.axhspan(372 - 85, 372 + 85, color=C_GRAY, alpha=0.22)
    ax.axhline(387, color=C_BLUE, lw=1, ls=':')
    ax.text(4.45, 395, 'noise floor of\nidentical weights', fontsize=7, ha='right', color='#555')
    for i, v in enumerate(vals):
        ax.text(i, v + 10, f'¥{v}', ha='center', fontsize=7.5)
    ax.set_xticks(range(5)); ax.set_xticklabels(mechs, fontsize=8)
    ax.set_ylim(0, 500); ax.set_ylabel('profit (¥)')
    ax.set_title('(b) weight updates: noise-dominated', fontsize=9)
    # (c) memorization decomposition
    ax = axes[2]
    ax.bar([0], [195], 0.5, color=C_GRAY, label='plain control')
    ax.bar([1], [240], 0.5, color=C_GREEN, label='honest generalization')
    ax.bar([1], [150], 0.5, bottom=240, color=C_RED, label='benchmark memorization')
    ax.text(0, 205, '¥195', ha='center', fontsize=8)
    ax.text(1, 395, '¥390', ha='center', fontsize=8)
    ax.annotate('39% memorized\n(RRSI critic)', xy=(1, 315), xytext=(1.55, 330),
                fontsize=7.5, color=C_RED, arrowprops=dict(arrowstyle='->', color=C_RED, lw=0.9))
    ax.set_xticks([0, 1]); ax.set_xticklabels(['JitRL control', 'JitRL mature'], fontsize=8.5)
    ax.set_xlim(-0.5, 2.3); ax.set_ylabel('profit (¥)')
    ax.set_title('(c) test-time gain decomposes', fontsize=9)
    ax.legend(frameon=False, fontsize=7.5, loc='upper left')
    save(fig, 'fig3_failures.png')


# ═══════════════ Fig 4: substrates ═══════════════
def fig4():
    fig, axes = plt.subplots(1, 3, figsize=(12.5, 3.6))
    # (a) dose-response
    ax = axes[0]
    n, prof = [0, 3, 6, 12, 19], [150, 600, 750, 750, 900]
    ax.plot(n, prof, 'o-', color=C_GREEN, lw=1.8, ms=5)
    for xi, yi in zip(n, prof):
        ax.annotate(f'¥{yi}', (xi, yi), textcoords='offset points', xytext=(0, 7),
                    ha='center', fontsize=7.5)
    ax.set_xlabel('verified-asset library size'); ax.set_ylabel('profit / 12 rounds (¥)')
    ax.set_title('(a) assets compound: 6×, ρ=0.96', fontsize=9)
    ax.set_ylim(0, 1000)
    # (b) JitRL accumulate slope
    ax = axes[1]
    acc = [300, 600, 450, 600, 150, 0, 300, 300, 300, 450]
    pln = [0, 300, 150, 150, 300, 300, 450, 150, 0, 150]
    cs_acc, cs_pln = np.cumsum(acc) / np.arange(1, 11), np.cumsum(pln) / np.arange(1, 11)
    ax.plot(range(1, 11), cs_acc, 'o-', color=C_PURPLE, lw=1.8, ms=4, label='JitRL (memory accumulates)')
    ax.plot(range(1, 11), cs_pln, 's-', color=C_GRAY, lw=1.8, ms=4, label='plain control')
    ax.set_xlabel('session'); ax.set_ylabel('cumulative mean profit (¥)')
    ax.set_title('(b) experience slope: 2.0× (p=0.037)', fontsize=9)
    ax.legend(frameon=False, fontsize=7.5)
    # (c) V2 vs frontier distributions (3-judge)
    ax = axes[2]
    rng = np.random.default_rng(1)
    v2 = [450,600,550,600,500,600,370,570,570,700,490,700,640,270,570,650,500,600,540,670,
          520,650,600,500,700,670,570,600,600,450,570,450,550,420,540,680,500,420,570,700]
    mimo = [370,480,440,560,560,480,340,420,370,500,220,380,400,540]
    for i, (d, c, lbl) in enumerate([(v2, C_PURPLE, f'FluxEidosV2 (n=40)\nmean ¥532'),
                                     (mimo, C_ORANGE, f'mimo-flash (n=14)\nmean ¥433')]):
        xs = rng.normal(i, 0.055, len(d))
        ax.scatter(xs, d, s=14, color=c, alpha=0.55, zorder=3)
        ax.hlines(np.mean(d), i - 0.2, i + 0.2, color=c, lw=2.4)
    ax.boxplot([v2, mimo], widths=0.42, showfliers=False,
               medianprops=dict(lw=0), whiskerprops=dict(alpha=0.4),
               capprops=dict(alpha=0.4), patch_artist=True,
               boxprops=dict(facecolor='none', alpha=0.35))
    ax.set_xticks([0, 1]); ax.set_xticklabels(['FluxEidosV2\n(3-judge, n=40)', 'mimo-v2.6-flash\n(3-judge, n=14)'], fontsize=8)
    ax.set_ylabel('profit per session (¥)')
    ax.set_title('(c) surpassing the frontier: p=0.0015, d=1.0', fontsize=9)
    save(fig, 'fig4_substrates.png')


# ═══════════════ Fig 6: judges ═══════════════
def fig6():
    rows = json.loads((ROOT / 'leaderboard' / 'data' / 'judge_triples.json').read_text())
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.0))
    # (a) judge-judge scatter with density
    ax = axes[0]
    m = np.array([r['mimo-v2.6-pro'] for r in rows])
    g = np.array([r['glm-5.3'] for r in rows])
    ax.scatter(m, g, s=16, alpha=0.45, color=C_BLUE, edgecolors='none')
    ax.plot([0, 10], [0, 10], color=C_GRAY, lw=0.9, ls='--')
    from scipy.stats import spearmanr
    rho, p = spearmanr(m, g)
    ax.set_xlabel('mimo-v2.6-pro rating'); ax.set_ylabel('glm-5.3 rating')
    ax.set_xlim(-0.5, 10.5); ax.set_ylim(-0.5, 10.5)
    ax.set_title(f'(a) cross-vendor agreement: ρ={rho:.2f} (n=283)', fontsize=9)
    # (b) family-bias gaps
    ax = axes[1]
    judges = ['mimo-v2.6-pro', 'glm-5.3', 'glm-5.3-flash']
    gaps = [-0.61, -0.25, -1.11]
    ax.barh(range(3), gaps, 0.5, color=[C_ORANGE, C_BLUE, C_BLUE])
    ax.axvline(0, color='k', lw=0.8)
    ax.set_yticks(range(3)); ax.set_yticklabels(judges, fontsize=8.5)
    ax.set_xlabel('rating gap: mimo-designs − our designs')
    for i, gp in enumerate(gaps):
        ax.text(gp - 0.05, i, f'{gp:+.2f} (n.s.)', ha='right', fontsize=8)
    ax.set_xlim(-1.7, 0.6)
    ax.set_title('(b) no family bias (gaps ≤ 0, n.s.)', fontsize=9)
    ax.grid(axis='y', visible=False)
    save(fig, 'fig6_judges.png')


if __name__ == '__main__':
    fig1(); fig2(); fig3(); fig4(); fig6()
    print('all figures done')
